Repository codersforcauses/coexist, pull requests merged in 2024-07, with the labels that each got.

#46 Issue 31 - Create Modal for Viewing RSVPs
  client/package.json
  client/src/components/main/RsvpListModal.tsx
  client/src/components/ui/BetterDialog.tsx
  client/src/components/ui/table.tsx
Labels: frontend

#66 Issue 55 create event page front end
  client/public/eventImageInsta.jpg
  client/src/pages/event.tsx
Labels: frontend

#73 Issue 71 - Add phone number field and migrations
  server/api/users/migrations/0005_extendeduser_phone.py
  server/api/users/migrations/0006_extendeduser_add_primary_key.py
  server/api/users/models.py
Labels: backend, difficulty:easy

#67 Issue 47 - Create User Endpoint
  server/api/urls.py
  server/api/users/serializers.py
  server/api/users/tests.py
  server/api/users/urls.py
  server/api/users/views.py
Labels: backend, enhancement, difficulty:easy

#81 Issue 80 - Fix up static file serving
  server/api/settings.py
Labels: backend, difficulty:easy

#90 Issue 89 - Add has_rsvp endpoint
  server/api/event/urls.py
  server/api/event/views.py
Labels: backend, enhancement

#100 Issue 99 fix further issues with rsvp endpoint
  server/api/event/urls.py
  server/api/event/views.py
Labels: backend, bug, enhancement
